spring:
  thymeleaf:
#    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
#    mode: HTML #模板
server:
  port: 8080

logging:
  config: classpath:logback.xml
  level:
    com:
      springboot: debug